FROM ubuntu:24.04

USER root

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    make \
    curl \
    ca-certificates \
    wget \
    && \
    apt-get clean && \
    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

USER ubuntu

RUN curl -fsSL https://install.julialang.org | sh -s -- --yes --default-channel=nightly
ENV PATH /home/ubuntu/.juliaup/bin:$PATH
RUN julia --version
